# Generated by Django 3.2.12 on 2022-03-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetail',
            old_name='youradress',
            new_name='youraddress',
        ),
    ]
